services:
  - type: web
    name: discord-songplay-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TOKEN
        sync: false
    # For health checks if needed
    healthCheckPath: /
    # Build command
    buildCommand: npm run build
    # Start command
    startCommand: npm start
